/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/
import { useGLTF } from '@react-three/drei'

export default  function React(props:any) {
  const { nodes, materials } = useGLTF('/models/react_logo.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['React-Logo_Material002_0'].geometry}
          material={materials['Material.002']}
          position={[0, 0, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[2,2, 2]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/react_logo.glb')